//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoWipe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrototype
    {
        public string product_type { get; set; }
        public string product_attr { get; set; }
    }
}
